### PR TITLE
Migrate typescript and bundle using esbuild

### PR DESCRIPTION
**Pull request by theMackabu**
- Update maidfile json command
- Migrate project to typescript
- Bundle code for package

Minor code cleanup as well

### CODE REVIEW

**Comment by kurucu** [comment]
Fantastic contribution, thank you @theMackabu.

It would be so lovely to have the ability to do testing with Panic objects, or at least mocked objects. Until then I'll have to do my best manually.
Going to check out and review, and then remove the sponsorship links too as part of this update. We'll make it a next major version, so please feel free to propose any other changes you were sitting on the fence over.

**Comment by kurucu** [comment]
Local uncommitted changes included having a go at testing 😂 I think I'll stash those for now.

**Comment by theMackabu** [comment]
> Fantastic contribution, thank you @theMackabu.
> 
> It would be so lovely to have the ability to do testing with Panic objects, or at least mocked objects. Until then I'll have to do my best manually. Going to check out and review, and then remove the sponsorship links too as part of this update. We'll make it a next major version, so please feel free to propose any other changes you were sitting on the fence over.

I was thinking about implementing #10 but as I thought about it more, I noticed the only way is to read the task file manually. Another idea was something that could parse tasks and turn them into nova tasks that anyone can use in the .nova folder for portability reasons.

**Comment by kurucu** [comment]
> I was thinking about implementing #10 but as I thought about it more, I noticed the only way is to read the task file manually. Another idea was something that could parse tasks and turn them into nova tasks that anyone can use in the .nova folder for portability reasons.

Not a bad idea at all actually - let me stew on that for a while. My working idea was to follow in your footsteps with Maidfile, and try to bundle something that could parse `.vscode/tasks.json` for us and interpret the output.

I'll commit back my changes today, and give us some time to think about other improvements before merging.

On a side note - things I've found so far:

- Nova extensions need README and CHANGELOG files. I've moved the readme, and will create a new one in the top level for the project itself. The CHANGELOG is copied from the top level into the built extension folder as part of the build step now.
-  The .acorn file is a source file for the icons, so I've put that in the /src folder so its not bundled with the extension
- Otherwise minor changes like modifying to v5 and removing sponsorship/funding links.
- Nova doesn't like you editing the project directory and activating the built extension within it for development (it sees them as a the same project, so just ignores you, but can't open the project folder as an extension because it's not one...).  Options as far as I can see: develop extension in another editor (yuck), move the built extension to the top-level (yuckier), or hopefully I find a workaround.

**Comment by kurucu** [comment]
> Nova doesn't like you editing the project directory and activating the built extension within it for development (it sees them as a the same project, so just ignores you, but can't open the project folder as an extension because it's not one...).  Options as far as I can see: develop extension in another editor (yuck), move the built extension to the top-level (yuckier), or hopefully I find a workaround.

Thankfully it's easy:

```sh
nova extension activate ./build/taskfinder.novaextension  
```

**Comment by kurucu** [comment]
Please take a look at my mods and see what you think. As I say, I won't merge this until thoughts settle around #10.

**Review by kurucu — APPROVED** [review]

**Comment by theMackabu** [comment]
> Please take a look at my mods and see what you think. As I say, I won't merge this until thoughts settle around #10.

the new readme is quite clean, and the command line workaround using the nova cli is quite smart (I was manually installing the extension every time). A vscode task parser as a embedded library could work, but we could only target script task types  right?

**Comment by theMackabu** [comment]
screenshot
Made the screenshot dark mode for our eyes. I also noticed tasks were not clearing on reload and duplicates were happening, fixed by clearing the tasks array.

**Comment by theMackabu** [comment]
hmm, taskfile and maidfile tasks seem to duplicate, ill find out why

**Comment by theMackabu** [comment]
I added a hacky fix to prevent duplication of tasks, as the task parser seem to run twice when the watcher reloads the task.

**Comment by kurucu** [comment]
> I added a hacky fix to prevent duplication of tasks, as the task parser seem to run twice when the watcher reloads the task.

I'll have a look as well this morning. Strange!

**Comment by theMackabu** [comment]
> > I added a hacky fix to prevent duplication of tasks, as the task parser seem to run twice when the watcher reloads the task.
> 
> I'll have a look as well this morning. Strange!

It also does not happen on the first time run, it happens after saving a file and the nova water reloads the tasks

**Comment by kurucu** [comment]
I've created a dummy maidfile but its failing with `No task called "butler" was found. Stop.` - butler seems to be hard coded - any clues?

**Comment by kurucu** [comment]
I've fixed the issue with the task file duplication - I think that Nova calls the script twice in quick succession. Both processes quickly clear the tasks array, and then they slowly each add one task to the array. Future executions run in isolation and so clear and then add the one item.

As a result, I've removed the class variable and put it in the method. Once I tidied up a bit, I realised that the method is only called in one place (provideTasks) and so just made provideTasks do all the work. You can undo that if you think it's a bad decision.

The other change, to create a method variable and return it at the end has fixed the parallel process issue. I can't apply this fix to the Maidfile provider, as I can't test it - so perhaps you can look at what I've done and use that for inspiration.

I've also fixed a few TS errors here and there, and tidied up the README a bit.

**Comment by theMackabu** [comment]
The problem with the maidfile as it was the wrong format, once fixing that I also removed the double method from the provider and applied a lint to all of it. It seems to work perfectly now without issues

**Review by kurucu — APPROVED** [review]

**Comment by kurucu** [comment]
That's a pretty solid effort - and a candidate for v5 I think, thank you again!

**Comment by theMackabu** [comment]
Not sure what else needs to be added, maybe support for other build systems like bob?

**Comment by kurucu** [comment]
> Not sure what else needs to be added, maybe support for other build systems like bob?

I was waiting to see if any more inspiration comes to us. I think I'll move your idea for Bob (https://bob.build, right?) to a new issue so we can discuss and hack around ideas like Bob, VSCode and more. 

When it comes to this PR, I'm going to merge it and call it v5, as it's a good baseline on which to build.

**Pull request merged**
